export function rowToApi(row, signedUrl) {
  return {
    employeeId: row.id,
    createdAt: row.created_at,
    name: row.name,
    fatherHusbandName: row.father_husband_name,
    dob: row.dob,
    sex: row.sex,
    placeOfBirth: row.place_of_birth,
    nationality: row.nationality,
    cnic: row.cnic,
    religion: row.religion,
    maritalStatus: row.marital_status,
    postAppliedFor: row.post_applied_for,
    department: row.department,
    salaryExpected: row.salary_expected,
    joiningDate: row.joining_date,
    availability: row.availability,
    contactTel: row.contact_tel,
    attendanceAllowance: row.attendance_allowance,
    address: row.address,
    education: row.education || [],
    employment: row.employment || [],
    emergencyName: row.emergency_name,
    emergencyRelation: row.emergency_relation,
    emergencyResTel: row.emergency_res_tel,
    emergencyBusTel: row.emergency_bus_tel,
    emergencyAddress: row.emergency_address,
    photoUrl: signedUrl || null,
  };
}
